const USER_ROLES = ["USER", "MODERATOR", "ADMIN"];

const CHECKPOINT_STATUSES = ["OPEN", "DELAYED", "CLOSED", "HAZARDOUS"];

const INCIDENT_CATEGORIES = [
  "ROAD_CLOSURE",
  "CHECKPOINT_DELAY",
  "ACCIDENT",
  "WEATHER_HAZARD",
  "MILITARY_ACTIVITY",
  "OTHER",
];

const INCIDENT_SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];

const INCIDENT_STATUSES = ["OPEN", "VERIFIED", "CLOSED"];

const INCIDENT_SOURCE_TYPES = ["MANUAL", "CROWDSOURCED", "EXTERNAL_API"];

const REPORT_CATEGORIES = INCIDENT_CATEGORIES;

const REPORT_MODERATION_STATUSES = [
  "PENDING",
  "APPROVED",
  "REJECTED",
  "DUPLICATE_REVIEW",
];

const REPORT_MODERATION_ACTIONS = ["APPROVE", "REJECT", "MARK_DUPLICATE"];

const REPORT_VOTE_TYPES = ["UP", "DOWN"];

const ALERT_STATUSES = ["PENDING", "READY", "SENT", "FAILED"];

const AUDIT_TARGET_TYPES = ["REPORT", "INCIDENT", "CHECKPOINT", "USER"];

const AUDIT_ACTION_TYPES = [
  "REPORT_APPROVED",
  "REPORT_REJECTED",
  "REPORT_MARKED_DUPLICATE",
  "INCIDENT_CREATED",
  "INCIDENT_VERIFIED",
  "INCIDENT_CLOSED",
  "CHECKPOINT_CREATED",
  "CHECKPOINT_STATUS_UPDATED",
];

module.exports = {
  USER_ROLES,
  CHECKPOINT_STATUSES,
  INCIDENT_CATEGORIES,
  INCIDENT_SEVERITIES,
  INCIDENT_STATUSES,
  INCIDENT_SOURCE_TYPES,
  REPORT_CATEGORIES,
  REPORT_MODERATION_STATUSES,
  REPORT_MODERATION_ACTIONS,
  REPORT_VOTE_TYPES,
  ALERT_STATUSES,
  AUDIT_TARGET_TYPES,
  AUDIT_ACTION_TYPES,
};
